USE SALES ;



SELECT * FROM CUSTOMERS ;

SELECT *FROM DATE ;


SELECT * FROM MARKETS ;

SELECT * FROM PRODUCTS ;

SELECT * FROM TRANSACTIONS ;


--->Q1 HOW MANY REVENU GENRATED IN EACH YEAR IN MILLION ?

SELECT YEAR(ORDER_DATE) AS YEAR , CONCAT(SUM(SALES_QTY)/1000 ,'K') AS TOTAL_QUANTITY , CONCAT(SUM(SALES_AMOUNT)/1000000 , 'M' ) AS TOTAL_REVENU FROM TRANSACTIONS
GROUP BY YEAR(ORDER_DATE) 
ORDER BY 3 DESC ;


--->Q2 HOW MUCH SALES HAPPEN IN EACH ZONE IN EACH YEAR ?

SELECT YEAR(ORDER_DATE) AS YEAR , ZONE , SUM(SALES_QTY) AS TOTAL_QUANTITY , SUM(SALES_AMOUNT) AS TOTAL_REVENUE
FROM TRANSACTIONS
INNER JOIN MARKETS
ON TRANSACTIONS.MARKETS_CODE = MARKETS.MARKETS_CODE
GROUP BY YEAR(ORDER_DATE) , ZONE 
ORDER BY YEAR(ORDER_DATE) ;


---Q3 HOW MANY REVENU HAPPEN IN EACH CITY  ;

SELECT YEAR(ORDER_DATE) AS YEAR , ZONE ,MARKETS_NAME AS CITY ,  SUM(SALES_QTY) AS TOTAL_QUANTITY , SUM(SALES_AMOUNT) AS TOTAL_REVENUE
FROM TRANSACTIONS
INNER JOIN MARKETS
ON TRANSACTIONS.MARKETS_CODE = MARKETS.MARKETS_CODE
GROUP BY YEAR(ORDER_DATE) , ZONE  , MARKETS_NAME
ORDER BY YEAR(ORDER_DATE) ;


SELECT MARKETS_NAME AS CITY , SUM(SALES_QTY) AS TOTAL_QUANTITY , SUM(SALES_AMOUNT) AS TOTAL_REVENUE
 FROM TRANSACTIONS
 INNER JOIN MARKETS
 ON TRANSACTIONS.MARKETS_CODE = MARKETS.MARKETS_CODE 
 GROUP BY MARKETS_NAME 
 ORDER BY 3 DESC ;

---Q4 REVENU PER PRODUCT IN MILLION 

SELECT PRODUCT_TYPE AS P_NAME ,SUM(SALES_AMOUNT), CONCAT(SUM(SALES_AMOUNT)/1000000 , 'M') AS TOTAL_REVENUE 
FROM TRANSACTIONS 
INNER JOIN PRODUCTS 
ON TRANSACTIONS.PRODUCT_CODE = PRODUCTS.PRODUCT_CODE 
GROUP BY PRODUCT_TYPE 
ORDER BY 2 DESC ; 



---Q5 TOP 5 CUSTOMER NAME AS PER THE REVENUE 

SELECT TOP 5 CUSTMER_NAME , CONCAT(SUM(SALES_AMOUNT)/1000000 , 'M') AS TOTAL_REVENUE 
FROM TRANSACTIONS
INNER JOIN CUSTOMERS 
ON TRANSACTIONS.CUSTOMER_CODE = CUSTOMERS.CUSTOMER_CODE
GROUP BY CUSTMER_NAME 
ORDER BY 2  DESC;

---Q6 TOP 10  DATE WHERE MAX TRANSACTION HAPPEN BY WHICH  CUSTOMER , HIS ZONE , CITY , 

SELECT TOP 10  ORDER_DATE , CUSTMER_NAME , ZONE , MARKETS_NAME AS CITY , PRODUCT_TYPE , SALES_QTY ,  SALES_AMOUNT 
FROM TRANSACTIONS 
INNER JOIN PRODUCTS 
ON TRANSACTIONS.PRODUCT_CODE = PRODUCTS.PRODUCT_CODE 
INNER JOIN MARKETS
ON TRANSACTIONS.MARKETS_CODE = MARKETS.MARKETS_CODE
INNER JOIN CUSTOMERS 
ON TRANSACTIONS.CUSTOMER_CODE = CUSTOMERS.CUSTOMER_CODE
ORDER BY SALES_AMOUNT DESC ;


---Q7 DELETE TRANSACTION WHERE SALES AMOUNT IS 0 OR LESS THAN 0 

SELECT * FROM TRANSACTIONS 
WHERE SALES_AMOUNT <=0 ;

DELETE FROM TRANSACTIONS
WHERE SALES_AMOUNT <=0 ;






